### PR TITLE
simple: Update to new AppData API.

### LINKED ISSUE #137: go tests fail: `TestNoRTMPListener` and `TestServerDisconnectMidStream`
blocks #136
```$ go test ./...
?   	github.com/livepeer/lpms/cmd/example	[no test files]
?   	github.com/livepeer/lpms/cmd/example/simple	[no test files]
?   	github.com/livepeer/lpms/cmd/transcoding	[no test files]
ok  	github.com/livepeer/lpms/core	(cached)
ok  	github.com/livepeer/lpms/ffmpeg	(cached)
HandShake: client signature does not match!
[hls @ 0x901ee00] Cannot use rename on non file protocol, this may lead to races and temporary partial files
WriteN, RTMP send error 32 (5 bytes)
WriteN, RTMP send error 32 (42 bytes)
RTMP_ReadPacket, failed to read RTMP packet body. len: 5604
HandShake: client signature does not match!
WriteN, RTMP send error 32 (5 bytes)
WriteN, RTMP send error 32 (42 bytes)
RTMP_ReadPacket, failed to read RTMP packet body. len: 5604
No application or playpath in URL!
RTMP_Connect0, failed to connect socket. 61 (Connection refused)
segmenter: Unable to open input
--- FAIL: TestNoRTMPListener (0.00s)
    video_segmenter_test.go:419: error was not nil; got  Unknown error occurred
HandShake: client signature does not match!
RTMP_ReadPacket, failed to read RTMP packet header
[flv @ 0xa002400] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
--- FAIL: TestServerDisconnectMidStream (0.11s)
    video_segmenter_test.go:464: Expected 'Input/output error' but instead got  <nil>
FAIL
FAIL	github.com/livepeer/lpms/segmenter	3.606s
ok  	github.com/livepeer/lpms/stream	(cached)
ok  	github.com/livepeer/lpms/transcoder	(cached)
ok  	github.com/livepeer/lpms/vidlistener	(cached)
ok  	github.com/livepeer/lpms/vidplayer	(cached)
```

### PR DESCRIPTION
**Pull request by j0sh**
Fixes compilation.

Closes #137

### CODE REVIEW

File: cmd/example/simple/simple.go [hunk 1]
```diff
@@ -34,9 +40,10 @@ func main() {
 	lpms := core.New(&core.LPMSOpts{WorkDir: fmt.Sprintf("%v/.tmp", dir)})
 
 	lpms.HandleRTMPPublish(
-		func(url *url.URL) (strmID string) {
+		func(url *url.URL) stream.AppData {
 			glog.Infof("Stream has been started!: %v", url)
-			return randString(10)
+			s := exampleStream(randString(10))
+			return &s
```
Comment (mkrufky) [inline cmd/example/simple/simple.go]: Please change this to:
```golang
return &exampleStream(randString(10))
```

Comment (mkrufky) [reply cmd/example/simple/simple.go]: Actually, I don't think the `&` is needed at all in this case - you are returning an interface.  Please see if:
```
return exampleStream(randString(10))
```
works without the ampersand.   If it does need the ampersand, it can be returned straight away without an intermediate.

**Comment by mkrufky** [comment]
If you add the phrase "closes #137 " to the description of this pull request, it will automatically close the issue that the PR is designed to resolve.

**Comment by mkrufky** [comment]
If you add the phrase "closes #137 " to the description of this pull request, it will automatically close the issue that the PR is designed to resolve when the PR get merged.

File: cmd/example/simple/simple.go (hunk 1 above)
Comment (j0sh) [reply cmd/example/simple/simple.go]: To do the second way, the `StreamID` method needs to be updated to take a non-pointer receiver. Not ideal for most normal usage but is OK for this case.

```diff
diff --git a/cmd/example/simple/simple.go b/cmd/example/simple/simple.go
index 5ec53f2..4ac4099 100644
--- a/cmd/example/simple/simple.go
+++ b/cmd/example/simple/simple.go
@@ -15,8 +15,8 @@ import (
 
 type exampleStream string
 
-func (t *exampleStream) StreamID() string {
-	return string(*t)
+func (t exampleStream) StreamID() string {
+	return string(t)
 }
 
 func randString(n int) string {
@@ -42,8 +42,7 @@ func main() {
 	lpms.HandleRTMPPublish(
 		func(url *url.URL) stream.AppData {
 			glog.Infof("Stream has been started!: %v", url)
-			s := exampleStream(randString(10))
-			return &s
+			return exampleStream(randString(10))
 		},
 
 		func(url *url.URL, rs stream.RTMPVideoStream) (err error) {
```
